FDP-94: Add monitoring and small fixes
OSGP/gxf-soap-bridge pull request #9
Opened 2023-11-30 12:37 UTC by jasperkamerling

2023-11-30 13:08 UTC, JelleHoffman approved these changes

2023-12-01 08:40 UTC, JelleHoffman submitted a review, later dismissed

2023-12-01 12:11 UTC, LucianoFavoroso approved these changes

2023-12-01 12:12 UTC, LucianoFavoroso submitted a review, later dismissed

2023-12-04 10:19 UTC, sanderv requested changes

2023-12-04 10:19 UTC, sanderv commented on application/src/main/kotlin/org/gxf/soapbridge/monitoring/MonitoringService.kt
> +            .description("Counts the successful requests to the Maki API")
Copy/paste?

2023-12-04 10:19 UTC, sanderv commented on application/src/main/kotlin/org/gxf/soapbridge/monitoring/MonitoringService.kt
> +    fun recordConnectionTime(startTime: Instant, context: String, successful: Boolean) {
Ik zou hier een naam kiezen die meer zegt in de richting van 'roundtrip' of 'response' over de proxy. Ja, de SOAP connection hebben we ook al die tijd open, maar dat is volgens mij niet wat we hier meten

2023-12-04 10:19 UTC, sanderv commented on application/src/main/kotlin/org/gxf/soapbridge/monitoring/MonitoringService.kt
Is dit voldoende om ook bijv. fail-rates uit te halen? Of moeten we wat counters toeveoegen?

2023-12-07 13:02 UTC, sanderv approved these changes

2023-12-07 14:13 UTC, LucianoFavoroso commented on application/src/test/kotlin/org/gxf/soapbridge/monitoring/MonitoringServiceTest.kt
> +        assertEquals(1.0, gauge.value())
Actual first param, Expected as second param.

2023-12-07 14:13 UTC, LucianoFavoroso commented on application/src/test/kotlin/org/gxf/soapbridge/monitoring/MonitoringServiceTest.kt
> +        assertEquals(1.0, gauge.value())
Actual first param, Expected as second param.

2023-12-07 14:13 UTC, LucianoFavoroso commented on application/src/test/kotlin/org/gxf/soapbridge/monitoring/MonitoringServiceTest.kt
> +        assertEquals(2.0, gauge.value())
Actual first param, Expected as second param.

2023-12-07 14:13 UTC, LucianoFavoroso commented on application/src/test/kotlin/org/gxf/soapbridge/monitoring/MonitoringServiceTest.kt
> +        assertEquals(0.0, gauge.value())
Actual first param, Expected as second param.

2023-12-07 14:13 UTC, LucianoFavoroso commented on application/src/test/kotlin/org/gxf/soapbridge/monitoring/MonitoringServiceTest.kt
> +}
new line

2023-12-07 15:05 UTC, LucianoFavoroso approved these changes

2023-12-07 15:08 UTC, merged